version: '3.7'

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    command: --ssl --sslcert /certs/portainer.pem --sslkey /certs/portainer.key
    ports:
      - "9444:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
      - "./certs:/certs:ro"
    networks:
      - my_network
    restart: always

  registry-1:
    image: registry:2
    container_name: registry-1
    restart: always
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry-1.pem
      REGISTRY_HTTP_TLS_KEY: /certs/registry-1.key
    ports:
      - "5000:5000"
    volumes:
      - registry1_data:/var/lib/registry
      - "./certs:/certs:ro"
    networks:
      - my_network

  registry-2:
    image: registry:2
    container_name: registry-2
    restart: always
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry-2.pem
      REGISTRY_HTTP_TLS_KEY: /certs/registry-2.key
    ports:
      - "5001:5000"
    volumes:
      - registry2_data:/var/lib/registry
      - "./certs:/certs:ro"
    networks:
      - my_network

  registry-3:
    image: registry:2
    container_name: registry-3
    restart: always
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry-3.pem
      REGISTRY_HTTP_TLS_KEY: /certs/registry-3.key
    ports:
      - "5002:5000"
    volumes:
      - registry3_data:/var/lib/registry
      - "./certs:/certs:ro"
    networks:
      - my_network

  docker-staging:
    build:
      context: .
      dockerfile: Dockerfile.dind
    container_name: docker-staging
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    ports:
      - "2375:2376"
    volumes:
      - staging_docker_data:/var/lib/docker
      - ./certs/docker-staging.pem:/certs/server/cert.pem
      - ./certs/docker-staging.key:/certs/server/key.pem
      - ./certs/rootCA.pem:/certs/server/ca.pem
    networks:
      - my_network

  docker-prod:
    build:
      context: .
      dockerfile: Dockerfile.dind
    container_name: docker-prod
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    ports:
      - "2376:2376"
    volumes:
      - prod_docker_data:/var/lib/docker
      - ./certs/docker-prod.pem:/certs/server/cert.pem
      - ./certs/docker-prod.key:/certs/server/key.pem
      - ./certs/rootCA.pem:/certs/server/ca.pem
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  staging_docker_data:
  prod_docker_data:
  portainer_data:
  registry1_data:
  registry2_data:
  registry3_data:
